// GENERATED by scripts/sync-client-teach.js from src/windows/shared — EDIT THE SOURCE, never this copy.
'use strict';
// Shared, PURE role-value resolver for the Teach wizard's suggested-teach auto-draw (reggie + gary
// → Oracle SIGN-OFF-W/COND 2026-09-26). The auto-draw looked up the import read by the TAUGHT type's
// EXACT field key; an UNTYPED import stores its reads under SPECULATIVE keys (invoice_date, order_date,
// po_date, worksheet_date, reference_number), so teaching that doc as a DIFFERENT type (e.g. Quote:
// quote_date / quote_number) missed even though the value WAS read. This routes the document's single
// primary DATE to the taught date ROLE and its primary REFERENCE to the ref ROLE — but ONLY when the
// candidates AGREE (fail-toward-manual on disagreement: a wrong date still LOCATES on the page and
// would poison the taught Stage-0.5 position, and the locate backstop cannot rescue it).
//
// No DOM, no IO — window.ImportRoleResolve for the classic window scripts, module.exports for node
// tests. Guarded by src/windows/shared/test_import_role_resolve.js. Consumed DEFENSIVELY by
// teach-ui/teach.js and mirrored to the detached client by scripts/sync-client-teach.js.
(function (root) {
  // A key that names a DATE by convention: <x>_date / date_<x> / bare "date". Used ONLY to WIDEN the
  // date candidate SCAN (never as the target-field trigger — Oracle C1: the trigger is strict role
  // equality). The value shape is checked separately, so a mislabelled *_date key holding junk cannot
  // be adopted.
  const DATE_KEY_RE = /(^|_)date($|_)/;

  // A numeric date: 3 parts split on / . or -, each 1-4 digits (mirrors teach _locateCandidates
  // `dateish` and config validation_patterns.date). A candidate must pass this before it counts.
  function looksLikeDate(v) {
    const parts = String(v == null ? '' : v).split(/[/.\-]/);
    return parts.length === 3 && parts.every(p => /^\d{1,4}$/.test(p));
  }

  // Compare-normalise. Dates fold separators to bare digits (18-04-2025 == 18/04/2025 == 18.04.2025).
  // Refs trim + uppercase, separators SIGNIFICANT (a ref's punctuation distinguishes it).
  function _normDate(v) { return String(v == null ? '' : v).replace(/[/.\-\s]/g, ''); }
  function _normRef(v)  { return String(v == null ? '' : v).trim().toUpperCase(); }

  // Build the role alias sets from every doc type (getAllDocTypes rows). Pure. Sets of STORED keys.
  // Drift-free: a new/custom type's role keys auto-extend the sets. REF is ENUMERATED only (every
  // type's ref_field_key ∪ 'reference_number') — deliberately NO *_number/*_no suffix rule, so
  // account_no / vat_no / phone (never a type's ref role) can never be picked as a reference.
  function buildRoleAliases(allDocTypes) {
    const dateAlias = new Set(['doc_date']);
    const refAlias  = new Set(['reference_number']);
    for (const t of (allDocTypes || [])) {
      if (t && t.date_field_key) dateAlias.add(t.date_field_key);
      if (t && t.ref_field_key)  refAlias.add(t.ref_field_key);
    }
    return { dateAlias, refAlias };
  }

  // Pick the document's single agreed value for a role from the import reads. role = 'date' | 'ref'.
  // Returns the raw stored value (a representative) when EVERY in-scope candidate normalises EQUAL,
  // else null (≥2 distinct = disagreement/ambiguity → the caller falls to a manual draw). Keys are
  // scanned in sorted order so the representative is deterministic for tests.
  function pickRoleImportValue(role, importValues, aliases) {
    if (!importValues || typeof importValues !== 'object') return null;
    const isDate = role === 'date';
    const alias  = (aliases && (isDate ? aliases.dateAlias : aliases.refAlias)) || new Set();
    const norm   = isDate ? _normDate : _normRef;
    let repr = null, seen = null;
    for (const k of Object.keys(importValues).sort()) {
      const inScope = alias.has(k) || (isDate && DATE_KEY_RE.test(k));
      if (!inScope) continue;
      const raw = importValues[k];
      if (raw == null || String(raw).trim() === '') continue;
      if (isDate && !looksLikeDate(raw)) continue;          // a *_date key holding junk is not a date
      const n = norm(raw);
      if (!n) continue;
      if (seen == null) { seen = n; repr = String(raw); }
      else if (n !== seen) return null;                     // ≥2 distinct → disagreement → manual
    }
    return repr;                                            // exactly one distinct, or null if none
  }

  // The call-site resolver (gary Option A). EXACT-KEY first (byte-identical passthrough — roles
  // ignored, so every currently-working type is untouched); else the STRICT role-equality fallback
  // (Oracle C1 — the trigger is `f.key === dateFieldKey` / `=== refFieldKey`, NOT _isDateField, so a
  // non-role date field like expiry_date never gets the role date bled onto it). Returns a non-empty
  // string or undefined. `opts` = { refFieldKey, dateFieldKey, dateAlias, refAlias }.
  function resolveImportValueForField(f, importValues, opts) {
    if (!f || !importValues) return undefined;
    const direct = importValues[f.key];
    if (typeof direct === 'string' && direct.trim() !== '') return direct;     // passthrough wins
    const o = opts || {};
    if (o.dateFieldKey && f.key === o.dateFieldKey) return pickRoleImportValue('date', importValues, o) || undefined;
    if (o.refFieldKey  && f.key === o.refFieldKey)  return pickRoleImportValue('ref',  importValues, o) || undefined;
    return undefined;                                       // neither role → no fallback (no bleed)
  }

  root.ImportRoleResolve = { buildRoleAliases, pickRoleImportValue, resolveImportValueForField, looksLikeDate };
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));

// Node/test interop (the browser path uses window.ImportRoleResolve).
if (typeof module !== 'undefined' && module.exports) {
  module.exports = (typeof window !== 'undefined' ? window : globalThis).ImportRoleResolve;
}
