// GENERATED by scripts/sync-client-search.js from src/windows/shared/search-ui — EDIT THE SOURCE, never this copy.
'use strict';
// Preview panel: document image viewer with page navigation + fields sidebar.
// SHARED SEARCH UI — IO only through window.SearchTransport (see searchState.js header).
// Capability gates (client parity): caps.singlePage / pageCount / find / spreadsheet — absent = true,
// so the core (every cap true) runs exactly the code path it always did.

// ── Fields sidebar ────────────────────────────────────────────────────────────

function renderPreviewFields(doc) {
  const scroll = document.getElementById('preview-fields-scroll');
  scroll.innerHTML = '';

  // Confidence band (enhanced Search only) — UNCOMMITTED docs only; a confirmed doc is
  // already checked + committed, so a detection % against it would mislead.
  if (window.SearchState.entitled && doc.overall_confidence != null && doc.status !== 'confirmed') {
    const lvl = confLevel(doc.overall_confidence);
    const w   = Math.max(4, Math.min(100, doc.overall_confidence));
    const band = document.createElement('div');
    band.className = `pf-confband ${lvl}`;
    band.innerHTML = `<span class="pf-label">Reading confidence</span>
      <span class="cb-meter"><i style="width:${w}%"></i></span><span class="cb-val">${doc.overall_confidence}%</span>`;
    scroll.appendChild(band);
  }

  // Fields render as one bordered TABLE — label left, value right (owner 2026-08-03: match
  // the client's tabular field panel). The .pf-fields container gives the table its frame; the
  // per-row layout is CSS. Core identity/role fields first, then any extra extracted fields.
  const fields = document.createElement('div');
  fields.className = 'pf-fields';
  _field(fields, 'Company',   doc.supplier_name);
  _field(fields, 'Type',      doc.type_name);
  _field(fields, 'Reference', doc.reference_number);
  _field(fields, 'Date',      doc.doc_date);
  _field(fields, 'Status',    doc.status);

  if (Array.isArray(doc.extractions) && doc.extractions.length) {
    // Skip keys surfaced as core fields above; show all others with a value.
    const coreKeys = new Set(['supplier_name', 'invoice_number', 'invoice_date',
                               'po_number', 'po_date', 'sales_order_number', 'order_date']);
    const extras = doc.extractions
      .filter(ex => !coreKeys.has(ex.field_key) && ex.display_value)
      .sort((a, b) => (b.confidence || 0) - (a.confidence || 0));
    for (const ex of extras) _field(fields, _keyLabel(ex.field_key), ex.display_value, ex.confidence, ex.validation_note);
  }
  scroll.appendChild(fields);
}

function _field(container, label, value, confidence, note) {
  const row = document.createElement('div');
  row.className = 'pf-row';
  // Per-field confidence tint (enhanced Search only): warn if a validation note,
  // otherwise by confidence level. Basic Search is left byte-for-byte unchanged.
  if (window.SearchState.entitled) {
    const lvl = note ? 'warn' : confLevel(confidence);
    if (lvl) row.classList.add('pf-tint', 'pf-' + lvl);
  }
  const confSpan = confidence != null ? `<span class="pf-conf">${confidence}%</span>` : '';
  row.innerHTML = `
    <span class="pf-label">${escHtml(label)}</span>
    <span class="pf-value${value ? '' : ' empty'}">${escHtml(value || '—')}${confSpan}</span>
    ${window.SearchState.entitled && note ? `<span class="pf-note">⚠ ${escHtml(note)}</span>` : ''}
  `;
  container.appendChild(row);
}

function _keyLabel(key) {
  return key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

// ── Page navigation ───────────────────────────────────────────────────────────

// The bottom bar carries the zoom controls (always shown while a doc is up) and the
// page controls (`.pn-pages`, shown only for multi-page docs).
function _syncPageNav() {
  const s   = window.SearchState;
  const nav = document.getElementById('page-nav');
  if (!s.currentPages.length) { nav.style.display = 'none'; return; }
  nav.style.display = '';                                    // reverts to the CSS flex row
  // Find-in-document is available whenever a page is shown (born-digital PDF text). The stepper counts
  // stay 0/0 with the ‹ › disabled until a term matches — the input itself is always ready to type in.
  // A transport that cannot find (caps.find === false) hides the whole Find cluster instead.
  const findOn = _cap('find');
  const mnav = document.getElementById('match-nav'); if (mnav) mnav.style.display = findOn ? '' : 'none';
  const msep = document.getElementById('match-sep'); if (msep) msep.style.display = findOn ? '' : 'none';
  const multi = s.currentPages.length > 1;
  document.querySelectorAll('#page-nav .pn-pages').forEach(el => { el.style.display = multi ? '' : 'none'; });
  if (multi) {
    document.getElementById('page-label').textContent = `${s.currentPage + 1} / ${s.currentPages.length}`;
    document.getElementById('btn-page-prev').disabled = s.currentPage === 0;
    document.getElementById('btn-page-next').disabled = s.currentPage === s.currentPages.length - 1;
  }
}

// LAZY per-page render: currentPages is a SPARSE array of length = page count; a hole is rendered on
// demand (getDocumentPage) the first time its page is shown, then cached for this selection. This is
// what keeps a big multi-page scan fast to OPEN — only page 1 renders up front, not all N pages
// (a 34-page doc was ~6.5s + 37MB over IPC when every page rendered on open).
async function _showPage(idx) {
  const s = window.SearchState;
  if (idx < 0 || idx >= s.currentPages.length) return;
  s.currentPage = idx;
  if (!s.currentPages[idx]) {
    const mine = s.selectedDoc;
    let uri = null;
    try { uri = await window.SearchTransport.getDocumentPage(mine.id, idx, SEARCH_RENDER_SCALE); } catch { /* leave the hole */ }
    if (s.selectedDoc !== mine || s.currentPage !== idx) return;   // a newer selection / page won meanwhile
    if (uri) s.currentPages[idx] = uri;
  }
  if (s.currentPages[idx]) {
    document.getElementById('preview-img').src = s.currentPages[idx];
    document.getElementById('preview-img-wrap').style.display = '';   // reverts to the CSS flex
    document.getElementById('preview-img-placeholder').style.display = 'none';
  }
  _syncPageNav();
}

// ── Zoom / scroll / pan (owner control model 2026-09-13) ───────────────────────
//   • mouse WHEEL  = scroll the document up/down (native overflow scroll — NOT zoom)
//   • RIGHT-drag   = pan (grab-scroll the pane; left-click untouched)
//   • ZOOM         = the +/−/Reset buttons ONLY
// Zoom is LAYOUT-based (we set the image WIDTH), not a CSS transform: a transform doesn't change the
// element's layout box, so the scroll container never gains anything to scroll. Sizing the image so it
// truly overflows the pane is what lets the wheel scroll it and the right-drag pan it.
let previewZoom = 1;
const ZOOM_MIN = 1, ZOOM_MAX = 4, ZOOM_STEP = 0.25;
// Render the preview at ~216 DPI (scale 3). The pane rasterises the page and CSS-zooms it, so more source
// pixels = crisper zoom — but scale 6 (432 DPI) rendered EVERY page up front (~2.5s + 15 MB over IPC for a
// 5-page doc = a slow open). 216 DPI is crisp on screen and to ~2x zoom; it only softens near max zoom, an
// acceptable trade for a ~4x faster open (fine detail is a click away via "open externally"). If deep-zoom
// sharpness is needed later, re-render the CURRENT page on zoom-in rather than raising this for all pages.
const SEARCH_RENDER_SCALE = 3;

// Size the page image to (fit-width × zoom). At zoom 1 this equals the old max-width:100% fit; above 1 the
// image exceeds the pane so the pane scrolls. Called on every image load and on each zoom change.
function _applyZoom() {
  const img  = document.getElementById('preview-img');
  const area = document.getElementById('preview-img-area');
  const lvl  = document.getElementById('zoom-level');
  if (lvl) lvl.textContent = Math.round(previewZoom * 100) + '%';
  if (!img || !area || !img.naturalWidth) return;
  const areaW = Math.max(50, area.clientWidth - 32);      // minus the 16px padding each side
  const fitW  = Math.min(img.naturalWidth, areaW);
  img.style.maxWidth = 'none';                            // override the CSS max-width:100% so it can grow
  img.style.width    = Math.round(fitW * previewZoom) + 'px';
}
function setPreviewZoom(z) {
  const area = document.getElementById('preview-img-area');
  // Keep the pane's centre point stable across a zoom step (so + / − feels anchored, not jumpy).
  let ax = 0.5, ay = 0.5;
  if (area && area.scrollWidth > area.clientWidth)  ax = (area.scrollLeft + area.clientWidth  / 2) / area.scrollWidth;
  if (area && area.scrollHeight > area.clientHeight) ay = (area.scrollTop  + area.clientHeight / 2) / area.scrollHeight;
  previewZoom = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, z));
  _applyZoom();
  if (area) {
    if (area.scrollWidth  > area.clientWidth)  area.scrollLeft = ax * area.scrollWidth  - area.clientWidth  / 2;
    if (area.scrollHeight > area.clientHeight) area.scrollTop  = ay * area.scrollHeight - area.clientHeight / 2;
  }
}
function resetPreviewView() {
  previewZoom = 1;
  _applyZoom();
  const area = document.getElementById('preview-img-area');
  if (area) { area.scrollLeft = 0; area.scrollTop = 0; }
}

// ── Search-term matches (jump to first / next-prev / highlight) ─────────────────
// The backend returns match boxes as PAGE FRACTIONS (0..1, top-left origin); we overlay them as % of
// the page image so they track the layout zoom. Born-digital PDFs only for now (text layer, no OCR).
let _matches = [];       // [{ page, x0, y0, x1, y1 }]
let _matchIdx = -1;      // active match index, -1 = none
let _pendingScroll = false;
let _activeHlEl = null;

function _clearMatches() {
  _matches = []; _matchIdx = -1; _activeHlEl = null; _pendingScroll = false;
  const layer = document.getElementById('preview-hl-layer'); if (layer) layer.textContent = '';
  _updateMatchNav();
}
function _updateMatchNav() {
  // The Find CLUSTER's visibility now tracks "a doc is shown" (see _syncPageNav) so the input stays
  // usable before any match. Here we only reflect the match COUNT + enable/disable the ‹ › steppers.
  const on = _matches.length > 0;
  const lbl = document.getElementById('match-label'); if (lbl) lbl.textContent = on ? `${_matchIdx + 1} / ${_matches.length}` : '0 / 0';
  const prev = document.getElementById('btn-match-prev'); if (prev) prev.disabled = !on;
  const next = document.getElementById('btn-match-next'); if (next) next.disabled = !on;
}
function _renderHighlights() {
  const layer = document.getElementById('preview-hl-layer');
  if (!layer) return;
  layer.textContent = ''; _activeHlEl = null;
  const page = window.SearchState.currentPage;
  _matches.forEach((m, i) => {
    if (m.page !== page) return;
    const b = document.createElement('div');
    b.className = 'pv-hl' + (i === _matchIdx ? ' active' : '');
    b.style.left = (m.x0 * 100) + '%'; b.style.top = (m.y0 * 100) + '%';
    b.style.width = ((m.x1 - m.x0) * 100) + '%'; b.style.height = ((m.y1 - m.y0) * 100) + '%';
    layer.appendChild(b);
    if (i === _matchIdx) _activeHlEl = b;
  });
}
function _scrollActiveIntoView() {
  if (!_activeHlEl) return;
  try { _activeHlEl.scrollIntoView({ block: 'center', inline: 'center' }); }
  catch { try { _activeHlEl.scrollIntoView(); } catch {} }
}
// Called by the img load handler: re-draw this page's highlights (size known) + honour a pending jump.
function _onPageImageReady() {
  _renderHighlights();
  if (_pendingScroll) { _pendingScroll = false; _scrollActiveIntoView(); }
}
function _gotoMatch(i) {
  if (!_matches.length) return;
  _matchIdx = ((i % _matches.length) + _matches.length) % _matches.length;
  _updateMatchNav();
  const m = _matches[_matchIdx];
  if (m.page !== window.SearchState.currentPage) {
    _pendingScroll = true;          // the new page image's load handler will scroll to it
    _showPage(m.page);
  } else {
    _renderHighlights();
    const img = document.getElementById('preview-img');
    if (img && img.complete && img.naturalWidth) _scrollActiveIntoView();
    else _pendingScroll = true;     // still loading — defer the scroll to the load handler
  }
}

// ── Find in THIS document (top-right input; searches only the open doc) ─────────
// Reuses the same per-doc backend + overlay as the list-term highlight (findInDocument →
// page-fraction match boxes). Born-digital PDF text only, same as the list-term path; a scanned
// page / office file yields 0 matches (the doc is still found by the list search). A2 (scanned
// OCR word-boxes) + A3 (client /v1) remain the follow-ups noted in the 09-13 DAY handover.
let _findTerm  = '';       // the term the current _matches belong to (so Enter can step vs re-search)
let _findTimer = null;
async function runDocFind(term) {
  const s = window.SearchState;
  const doc = s.selectedDoc;
  const input = document.getElementById('inp-find-doc');
  term = String(term || '').trim();
  if (!doc || !term) { _findTerm = ''; _clearMatches(); if (input) input.classList.remove('no-match'); return; }
  let res;
  try { res = await window.SearchTransport.findInDocument(doc.id, term); }
  catch { _findTerm = term; _clearMatches(); return; }
  if (s.selectedDoc !== doc) return;          // a newer selection now owns the preview pane
  _findTerm = term;
  _matches  = (res && Array.isArray(res.matches)) ? res.matches : [];
  if (_matches.length) { _gotoMatch(0); if (input) input.classList.remove('no-match'); }
  else { _matchIdx = -1; const layer = document.getElementById('preview-hl-layer'); if (layer) layer.textContent = '';
         _updateMatchNav(); if (input) input.classList.add('no-match'); _noteFindOutcome(res, input); }
}

// A transport may report that a find could not complete in time (a long scanned document over the network —
// the detached client's /v1 lane): say so instead of a silent "0 / 0". The core's in-process find never returns
// this kind, so the core path is unchanged. (Oracle 2026-09-13 seam 8.)
function _noteFindOutcome(res, input) {
  const lbl = document.getElementById('match-label');
  if (res && res.kind === 'timeout') {
    if (lbl) lbl.textContent = 'took too long';
    if (input) input.title = 'Find took too long on this scanned document — try a shorter word, or open the document.';
  } else if (input && input.title && /took too long/.test(input.title)) {
    input.title = 'Find text in this document (PDF text). Enter = next match, Shift+Enter = previous, Esc = clear.';
  }
}

function initPageNav() {
  document.getElementById('btn-page-prev').addEventListener('click', () =>
    _showPage(window.SearchState.currentPage - 1));
  document.getElementById('btn-page-next').addEventListener('click', () =>
    _showPage(window.SearchState.currentPage + 1));

  document.getElementById('btn-zoom-in') ?.addEventListener('click', () => setPreviewZoom(previewZoom + ZOOM_STEP));
  document.getElementById('btn-zoom-out')?.addEventListener('click', () => setPreviewZoom(previewZoom - ZOOM_STEP));
  document.getElementById('btn-zoom-reset')?.addEventListener('click', resetPreviewView);
  document.getElementById('btn-match-prev')?.addEventListener('click', () => _gotoMatch(_matchIdx - 1));
  document.getElementById('btn-match-next')?.addEventListener('click', () => _gotoMatch(_matchIdx + 1));

  // Find-in-document input: debounced live search; Enter steps to the next match (Shift+Enter previous)
  // once a term is matched, Esc clears. stopPropagation on the nav keys so the list's ↑/↓ doc-cycling
  // and other global shortcuts don't fire while the operator is typing in the box.
  const findInput = document.getElementById('inp-find-doc');
  if (findInput) {
    findInput.addEventListener('input', () => {
      clearTimeout(_findTimer);
      const v = findInput.value;
      _findTimer = setTimeout(() => runDocFind(v), 220);
    });
    findInput.addEventListener('keydown', (e) => {
      if (e.key === 'Enter') {
        e.preventDefault(); e.stopPropagation();
        clearTimeout(_findTimer);
        const v = findInput.value.trim();
        if (_matches.length && v === _findTerm) _gotoMatch(_matchIdx + (e.shiftKey ? -1 : 1));
        else runDocFind(v);
      } else if (e.key === 'Escape') {
        e.stopPropagation();
        findInput.value = ''; runDocFind('');
      } else if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
        e.stopPropagation();   // let the caret move / don't cycle documents while typing
      }
    });
  }

  const img  = document.getElementById('preview-img');
  const area = document.getElementById('preview-img-area');
  const hasDoc = () => window.SearchState.currentPages.length > 0;
  // On each page image load (natural size now known): re-fit to the current zoom, then re-draw this
  // page's search highlights and honour any pending "jump to match" scroll.
  if (img) img.addEventListener('load', () => { _applyZoom(); _onPageImageReady(); });
  // The wheel now scrolls natively (no handler) — we only block native image drag + the context menu so
  // right-drag can pan without popping a menu.
  area.addEventListener('contextmenu', (e) => { if (hasDoc()) e.preventDefault(); });
  area.addEventListener('dragstart',   (e) => e.preventDefault());
  // Right-click drag = grab-scroll (pan). Drag the page the way your hand pushes it.
  let panStart = null;
  area.addEventListener('mousedown', (e) => {
    if (e.button !== 2 || !hasDoc()) return;
    panStart = { x: e.clientX, y: e.clientY, sl: area.scrollLeft, st: area.scrollTop };
    area.style.cursor = 'grabbing';
    e.preventDefault();
  });
  window.addEventListener('mousemove', (e) => {
    if (!panStart) return;
    area.scrollLeft = panStart.sl - (e.clientX - panStart.x);
    area.scrollTop  = panStart.st - (e.clientY - panStart.y);
  });
  window.addEventListener('mouseup', () => { if (panStart) { panStart = null; area.style.cursor = ''; } });
}

// ── Document selection ────────────────────────────────────────────────────────

async function selectDoc(doc) {
  const s = window.SearchState;
  s.selectedDoc = doc;
  let mine = doc;     // stale-selection guard: a newer click reassigns s.selectedDoc, so a
                      // late-resolving fetch for THIS doc must not clobber the newer render.
                      // (let, not const: after the fetch we upgrade both s.selectedDoc AND mine to
                      // the merged doc in lockstep, so the guard still fires on a genuinely newer click.)

  document.querySelectorAll('.result-item').forEach(el =>
    el.classList.toggle('active', parseInt(el.dataset.id) === doc.id));

  document.getElementById('preview-empty').style.display = 'none';
  document.getElementById('preview-doc').style.display   = '';

  const wrap = document.getElementById('preview-img-wrap');
  const ph   = document.getElementById('preview-img-placeholder');
  wrap.style.display = 'none';
  ph.style.display   = '';
  ph.innerHTML       = '<div class="spinner"></div>';
  ph.classList.remove('xlsx-ph');            // drop any prior spreadsheet-grid layout override
  resetPreviewView();                        // each new document opens at 100%, un-panned
  _clearMatches();                           // drop the previous doc's search highlights

  // The fetch sequence is wrapped so ANY failure (a missing IPC handler after a stale-main
  // update, a DB hiccup, the doc deleted mid-click, an IPC error) shows an honest state
  // instead of leaving the spinner forever — the silent-failure class Chris keeps catching.
  try {
    const full = await window.SearchTransport.getDocumentDetail(doc.id);   // PROJECTED — no paths/ocr_text (Document-detail DTO)
    if (s.selectedDoc !== mine) return;   // a newer selection now owns the preview pane
    // `full` (getDocumentDetail) now carries type_name (previewService resolves it) alongside the
    // extractions; the passed `doc` may be a BARE {id} from a mailbox/workflow row. Merge ONCE and use
    // it for ALL sub-renders — passing the bare doc to renderActions/onDocShown was why the mailbox
    // preview showed status "Unknown" and subtitle "Document —" (Chris r2 vet item A).
    const merged = { ...doc, ...(full || {}) };
    s.selectedDoc = merged;   // upgrade the live selection AND the guard token together, so a
    mine = merged;            // genuinely newer click still trips the `!== mine` stale guards below.
    renderPreviewFields(merged);
    window.SearchActions.renderActions(merged);

    // LAZY PAGE LOADING (owner 2026-09-13: big multi-page scans were slow to show ANYTHING because EVERY
    // page rendered up front — ~6.5s + 37MB over IPC for a 34-page doc; a single page is ~0.3s). For ANY
    // PDF we render + paint page 1 FIRST, independent of a known page_count — a separated original /
    // pre-mig-37 doc can have page_count NULL, and must NOT fall back to rendering every page before
    // showing. Other pages render on demand in _showPage. When the count is known we size a sparse array
    // so nav is live at once; when it's unknown we show page 1, then discover the rest in the BACKGROUND
    // (page 1 is already visible, so the user is never blocked). Images / office = one cheap render.
    // A transport without a single-page read (caps.singlePage === false) takes the full-render path.
    const _pageCount = Number(merged.page_count) || 0;
    const _isPdf = /\.pdf$/i.test(merged.original_filename || merged.stored_filename || '');
    if (_isPdf && _cap('singlePage')) {
      const first = await window.SearchTransport.getDocumentPage(doc.id, 0, SEARCH_RENDER_SCALE);
      if (s.selectedDoc !== mine) return;
      if (first) {
        s.currentPages = _pageCount > 1 ? new Array(_pageCount) : [first];   // sparse when count known
        s.currentPages[0] = first;
        s.currentPage = 0;
        if (_pageCount <= 1 && _cap('pageCount')) {
          // Count unknown (NULL/0 — e.g. a Quick File doc whose page count was never recorded): PROBE the
          // count cheaply (open the PDF, read len, NO render) so page nav appears at once and the rest
          // render on demand in _showPage. Avoids rendering every page in the background just to learn the
          // count (that made nav take ~15s on a 34-page doc). Staleness-guarded; probe failure → single page.
          window.SearchTransport.getDocumentPageCount(doc.id).then((cnt) => {
            if (s.selectedDoc !== mine) return;
            if (Number.isFinite(cnt) && cnt > 1) {
              const arr = new Array(cnt);
              arr[0] = s.currentPages[0];        // keep the page 1 already rendered
              s.currentPages = arr;
              _syncPageNav();
            }
          }).catch(() => { /* page 1 already shown; nav stays single */ });
        }
      } else {                                          // page-1 render failed — fall back to the full render
        s.currentPages = await window.SearchTransport.getDocumentPages(doc.id, null, null, SEARCH_RENDER_SCALE);
        if (s.selectedDoc !== mine) return;
        s.currentPage = 0;
      }
    } else {
      // DE-PATHED (owner 2026-08-02): rows no longer carry paths; fetch by docId alone — an
      // unresolvable file simply yields []. One render call (single page / image = cheap).
      s.currentPages = await window.SearchTransport.getDocumentPages(doc.id, null, null, SEARCH_RENDER_SCALE);
      if (s.selectedDoc !== mine) return;
      s.currentPage = 0;
    }

    if (s.currentPages.length > 0) {
      await _showPage(0);
      // Seed the Find-in-document box with the active list term, so what's highlighted matches the box
      // (and the operator can edit it to search within this doc). Empty when opened without a search.
      const q = s.query || '';
      const findInput = document.getElementById('inp-find-doc');
      if (findInput) { findInput.value = q; findInput.classList.remove('no-match'); }
      // Jump to / highlight the active search term (born-digital PDFs; best-effort, staleness-guarded).
      if (q && _cap('find')) {
        try {
          const res = await window.SearchTransport.findInDocument(doc.id, q);
          if (s.selectedDoc !== mine) return;    // a newer selection now owns the pane
          _findTerm = q;
          _matches = (res && Array.isArray(res.matches)) ? res.matches : [];
          if (_matches.length) _gotoMatch(0); else { _updateMatchNav(); if (findInput) findInput.classList.add('no-match'); _noteFindOutcome(res, findInput); }
        } catch { _clearMatches(); }
      }
    } else {
      // No image pages. An .xlsx has no rendered page but we CAN show its cells (route 1, dependency-
      // free grid). Anything else keeps the honest "no preview" note.
      const shown = await _tryRenderSpreadsheet(merged, ph);
      if (s.selectedDoc !== mine) return;
      if (!shown) {
        ph.style.display = '';
        ph.classList.remove('xlsx-ph');
        ph.innerHTML = 'No preview available';
      }
      document.getElementById('page-nav').style.display = 'none';
    }
    // Stamped/original toggle (Workflow+Stamping redesign): shows when the doc carries ≥1 stamp and
    // defaults the preview to the stamped version. Non-fatal + staleness-guarded inside.
    if (window.SearchStamp) { try { window.SearchStamp.onDocShown(merged); } catch (e) { console.error('stamp toggle:', e); } }
  } catch (err) {
    if (s.selectedDoc !== mine) return;   // don't overwrite a newer selection's state
    _showPreviewLoadError(ph, doc, err);
  }
}

// Honest, recoverable failure state in place of the eternal spinner. A missing IPC handler
// is the stale-main class (main-process code updated, app not yet restarted) — say so
// plainly; everything else gets a generic retry. Always falls back to the generic message
// so a changed Electron error string can never reintroduce a blank/misleading pane.
function _showPreviewLoadError(ph, doc, err) {
  const msg = String((err && err.message) || err || '');
  const staleMain = /No handler registered/i.test(msg);
  const title  = staleMain ? 'The app was updated — restart to finish'
                           : "Couldn't load this document";
  const detail = staleMain ? 'Close and reopen Scan Finder to load the latest update.'
                           : (msg || 'Try again, or reopen Search.');
  ph.style.display = '';
  ph.innerHTML = `<div class="pv-load-error">
      <div class="pe-title">${escHtml(title)}</div>
      <div class="pe-detail">${escHtml(detail)}</div>
      <button type="button" class="pe-retry">Try again</button>
    </div>`;
  document.getElementById('preview-img-wrap').style.display = 'none';
  document.getElementById('page-nav').style.display = 'none';
  const retry = ph.querySelector('.pe-retry');
  if (retry) retry.addEventListener('click', () => selectDoc(doc));
}

// ── Spreadsheet (.xlsx) grid preview ────────────────────────────────────────────
// A dependency-free cell grid for a Quick File .xlsx (route 1, 2026-09-13): the backend parses the
// workbook into capped rows; here we draw it as a scrollable table with column letters + row numbers,
// and a tab per sheet. Values only (no number-format/style fidelity) — enough to read the data.
function _colLetter(i) { let s = ''; i++; while (i > 0) { const r = (i - 1) % 26; s = String.fromCharCode(65 + r) + s; i = Math.floor((i - 1) / 26); } return s; }

function _sheetTableHtml(sheet) {
  const rows = sheet.rows || [];
  const width = rows.reduce((w, r) => Math.max(w, r.length), 0);
  // A <colgroup> drives the (fixed-layout) column widths so each column is drag-resizable. col 0 = the
  // row-number gutter; the data columns start at index 1. The table gets an EXPLICIT total width (= sum of
  // the cols) so a widened column grows the table (→ horizontal scroll) instead of the fixed layout just
  // redistributing width inside the container (which made a drag look like it did nothing).
  const _total = 46 + width * 132;
  let h = `<table class="xlsx-table" style="width:${_total}px"><colgroup><col style="width:46px">`;
  for (let c = 0; c < width; c++) h += '<col style="width:132px">';
  h += '</colgroup><tbody>';
  h += '<tr><td class="xlsx-corner"></td>';
  for (let c = 0; c < width; c++) h += `<td class="xlsx-colhdr">${_colLetter(c)}<span class="xlsx-col-resize" data-col="${c}" title="Drag to resize"></span></td>`;
  h += '</tr>';
  for (let ri = 0; ri < rows.length; ri++) {
    h += `<tr><td class="xlsx-rownum">${ri + 1}</td>`;
    for (let c = 0; c < width; c++) h += `<td>${escHtml(rows[ri][c] || '')}</td>`;
    h += '</tr>';
  }
  h += '</tbody></table>';
  return h;
}

// Drag-resize the spreadsheet columns: each header's right-edge handle sets its <col>'s width.
function _wireColResize(ph) {
  ph.querySelectorAll('.xlsx-col-resize').forEach((handle) => {
    handle.addEventListener('mousedown', (e) => {
      e.preventDefault(); e.stopPropagation();
      const table = handle.closest('table');
      const cols = table && table.querySelectorAll('colgroup > col');
      const col = cols && cols[parseInt(handle.dataset.col, 10) + 1];   // +1 skips the row-number gutter
      if (!col) return;
      const startX = e.clientX;
      const startW = parseInt(col.style.width, 10) || 132;
      const startTableW = parseInt(table.style.width, 10) || table.offsetWidth;
      const move = (ev) => {
        const newW = Math.max(40, startW + (ev.clientX - startX));
        col.style.width = newW + 'px';
        table.style.width = (startTableW + (newW - startW)) + 'px';   // grow the table so the change shows
      };
      const up = () => {
        window.removeEventListener('mousemove', move); window.removeEventListener('mouseup', up);
        document.body.style.cursor = '';
      };
      window.addEventListener('mousemove', move); window.addEventListener('mouseup', up);
      document.body.style.cursor = 'col-resize';
    });
  });
}

async function _tryRenderSpreadsheet(doc, ph) {
  const fn = doc.original_filename || doc.stored_filename || '';
  if (!/\.xlsx$/i.test(fn)) return false;           // grid preview is xlsx-only
  if (!_cap('spreadsheet')) return false;           // a transport without a grid read → the honest "no preview"
  let grid = null;
  try { grid = await window.SearchTransport.getSpreadsheetGrid(doc.id); } catch { return false; }
  if (window.SearchState.selectedDoc !== doc) return true;   // a newer selection owns the pane
  if (!grid || !Array.isArray(grid.sheets) || !grid.sheets.length) return false;
  const multi = grid.sheets.length > 1;
  const tabs = multi
    ? `<div class="xlsx-tabs">${grid.sheets.map((s, i) =>
        `<button type="button" class="xlsx-tab${i === 0 ? ' active' : ''}" data-sheet="${i}">${escHtml(s.name)}</button>`).join('')}</div>`
    : '';
  const panels = grid.sheets.map((s, i) =>
    `<div class="xlsx-scroll" data-sheet="${i}"${i === 0 ? '' : ' hidden'}>${_sheetTableHtml(s)}</div>`).join('');
  const note = grid.truncated
    ? '<div class="xlsx-note">Large spreadsheet — showing the first rows and columns. Open the file to see everything.</div>'
    : '';
  ph.style.display = '';
  ph.classList.add('xlsx-ph');
  ph.innerHTML = `<div class="xlsx-preview">${tabs}<div class="xlsx-body">${panels}</div>${note}</div>`;
  _wireColResize(ph);   // make every sheet's columns drag-resizable
  if (multi) {
    ph.querySelectorAll('.xlsx-tab').forEach((btn) => btn.addEventListener('click', () => {
      const idx = btn.dataset.sheet;
      ph.querySelectorAll('.xlsx-tab').forEach((b) => b.classList.toggle('active', b === btn));
      ph.querySelectorAll('.xlsx-scroll').forEach((p) => { p.hidden = p.dataset.sheet !== idx; });
    }));
  }
  return true;
}

window.SearchPreview = { selectDoc, renderPreviewFields, initPageNav };
