// GENERATED by scripts/sync-client-search.js from src/windows/shared/search-ui — EDIT THE SOURCE, never this copy.
'use strict';
// Search UI bootstrap — the app-agnostic part of the old Search-window renderer.js: seeds the doc-type
// dropdown, wires the inputs/rail/page-nav, runs the first search, then resolves the permission state
// (entitlement / role / stamp / print) that gates the action buttons. SHARED SEARCH UI — IO only through
// window.SearchTransport (see searchState.js header).
//
// Each host page (core Search window, client pop-out) calls window.SearchUI.init(opts) LAST, after every
// script has loaded, with hooks for what is app-specific:
//   opts.initialQuery      async () => string|null   — a term to pre-fill (core: the Quick-find deep-link)
//   opts.onWorkflowEntitled async () => void         — runs once the workflow add-on is known licensed
//                                                      (core: SearchWorkflow/SearchMailbox init + the counts push)
//   opts.afterInit         async () => void          — runs at the very end (core: the mailbox view deep-link)
// The ORDER below is load-bearing and identical to the pre-extraction renderer.js: results populate
// FIRST (they depend only on the query), the permission checks follow without holding up the list.

// ── Arrow-key document cycling (same as the rail ↑/↓; mirrors the Review window) ──
// Only fires outside text-entry controls so typing in the search box is unaffected.
function _installSearchKeys() {
  document.addEventListener('keydown', (e) => {
    const t = e.target;
    if (t && (t.isContentEditable || t.tagName === 'INPUT' || t.tagName === 'TEXTAREA' || t.tagName === 'SELECT')) return;
    if (e.repeat || e.ctrlKey || e.metaKey || e.altKey) return;
    if (e.key === 'ArrowUp')        { e.preventDefault(); window.SearchResults.cycleSelection(-1); }
    else if (e.key === 'ArrowDown') { e.preventDefault(); window.SearchResults.cycleSelection(1); }
  });
}

// ── Expandable details column — drag the grip to widen/narrow the sidebar ─────────
// The sidebar is docked RIGHT, so its width grows as the grip is dragged left. Width
// persists in localStorage (clamped) so a chosen width survives reopening.
function _installSidebarResizer() {
  const sidebar = document.getElementById('preview-sidebar');
  const grip    = document.getElementById('sidebar-resizer');
  if (!sidebar || !grip) return;
  const MIN = 220, MAX = 620;
  const saved = parseInt(localStorage.getItem('search_sidebar_width'), 10);
  if (saved >= MIN && saved <= MAX) sidebar.style.width = saved + 'px';
  let dragging = false, rightEdge = 0;
  grip.addEventListener('mousedown', (e) => {
    dragging = true; rightEdge = sidebar.getBoundingClientRect().right; e.preventDefault();
    document.body.style.cursor = 'col-resize'; document.body.style.userSelect = 'none';
  });
  window.addEventListener('mousemove', (e) => {
    if (!dragging) return;
    const w = Math.max(MIN, Math.min(MAX, rightEdge - e.clientX));
    sidebar.style.width = w + 'px';
  });
  window.addEventListener('mouseup', () => {
    if (!dragging) return;
    dragging = false; document.body.style.cursor = ''; document.body.style.userSelect = '';
    localStorage.setItem('search_sidebar_width', String(parseInt(sidebar.style.width, 10) || 280));
  });
}

// Refresh results when the window regains focus. A confirm / auto-file ("filed themselves") in Review or
// the main window changes the confirmed set, but Search gets NO push signal for it (review-count-changed
// reaches only main + review) — so a just-confirmed doc looked missing until Search was reopened. Re-run
// the CURRENT search when the user returns to this window, but ONLY when the results list is idle: never
// while typing a query, never in the mailbox view, and never while a document is selected/previewed (so it
// can't yank a doc you are reading). Debounced.
let _refocusT = null;
function _refreshResultsOnReturn() {
  clearTimeout(_refocusT);
  _refocusT = setTimeout(() => {
    try {
      const ae = document.activeElement;
      if (ae && (ae.tagName === 'INPUT' || ae.tagName === 'TEXTAREA')) return;   // mid-typing
      if (document.body.classList.contains('mailbox-mode')) return;              // mailbox view owns the pane
      if (window.SearchState && window.SearchState.selectedDoc) return;          // viewing a doc — don't reset
      window.SearchQuery.doSearch();
    } catch { /* best-effort */ }
  }, 200);
}
function _installRefocusRefresh() {
  window.addEventListener('focus', _refreshResultsOnReturn);
  document.addEventListener('visibilitychange', () => { if (!document.hidden) _refreshResultsOnReturn(); });
}

async function _loadDocTypes() {
  const types = await window.SearchTransport.getAllDocTypes();
  const sel   = document.getElementById('inp-type');
  for (const t of types) {
    const opt       = document.createElement('option');
    opt.value       = t.slug;
    opt.textContent = t.name;
    sel.appendChild(opt);
  }
}

async function _searchInit(opts) {
  // The type filter is optional: a transport that cannot list types (a read-only client — /v1/doc-types is
  // writer-gated) must not stop the whole screen from booting. The core's bridge never refuses, so this is
  // byte-identical on the core.
  try { await _loadDocTypes(); } catch { /* the dropdown keeps "All types" */ }
  // POPULATE RESULTS FIRST — they depend only on the query, not on entitlement/stamp/print (which only
  // gate the action buttons). doSearch used to run AFTER getEntitlement + authGetCurrentUser + stamp.can
  // (→ verifyAuditChain, whose cost grows with the audit log) + printAvailable, so on a busy install the
  // results list took a while to populate. Init the inputs/rail, pre-fill, and search NOW; the permission
  // checks below then run without holding up the list.
  window.SearchPreview.initPageNav();
  window.SearchQuery.initInputs();
  window.SearchResults.initRail();
  try {
    const q0 = opts.initialQuery ? await opts.initialQuery() : null;
    if (q0) { const el = document.getElementById('inp-fulltext'); if (el) el.value = q0; }
  } catch { /* no target */ }
  window.SearchQuery.doSearch();
  // Entitlements drive the experience, and SEARCH and WORKFLOW are SEPARATE add-ons:
  //  • search   → the enhanced Search surface (confidence signatures, validation notes);
  //  • workflow → the mailbox + approval actions. The workflow UI appears ONLY when the
  //    workflow add-on is licensed, so a search-only (or unlicensed) install shows NO
  //    mailbox/workflow mention at all.
  try {
    const e = await window.SearchTransport.getEntitlement();
    window.SearchState.entitled = !!(e && e.entitled);                                // search
    window.SearchState.workflowEntitled = !!(e && e.workflow && e.workflow.entitled); // workflow add-on
  } catch { window.SearchState.entitled = false; window.SearchState.workflowEntitled = false; }
  // The results painted BEFORE the entitlement was known (results-first ordering), so the enhanced search's
  // confidence pips were missing until the next search. Re-decorate the same rows once, now that it is known.
  if (window.SearchState.entitled && window.SearchResults.redecorate) { try { window.SearchResults.redecorate(); } catch {} }
  try { const u = await window.SearchTransport.authGetCurrentUser(); window.SearchState.role = u && u.role; } catch { /* ignore */ }
  // Stamp permission (Workflow+Stamping redesign): drives whether the "Stamp" option is shown at all.
  // A core capability (not the add-on); the main process re-checks on every place. A transport without
  // stamping (caps.stamps === false) never offers it.
  if (_cap('stamps')) {
    try { window.SearchState.canStamp = !!(await window.SearchTransport.stamp.can()).canStamp; } catch { window.SearchState.canStamp = false; }
  } else { window.SearchState.canStamp = false; }
  // Printing (Print-Slice 1): read once so renderActions can show/hide the Search Print button. The main
  // process re-checks printing_enabled on every print, so this is display-only.
  if (_cap('print')) {
    try { window.SearchState.printAvailable = !!(await window.SearchTransport.printAvailable?.()); } catch { window.SearchState.printAvailable = false; }
  } else { window.SearchState.printAvailable = false; }
  // Recycle bin is for the people who can delete (Admin/Edit) — on a transport that has a bin.
  if ((window.SearchState.role === 'admin' || window.SearchState.role === 'edit') && _cap('bin')) {
    const rb = document.getElementById('btn-recycle'); if (rb) rb.style.display = '';
  }
  if (window.SearchState.entitled) document.body.classList.add('wf-on');              // enhanced search
  if (window.SearchState.workflowEntitled) {
    document.body.classList.add('workflow-on');                                       // mailbox + approvals
    // The shared workflow + mailbox modules (S4): approvals in the action panel / Send-or-stamp popup, the
    // mailbox toggle. Cross-user freshness (Slice 1): ANY workflow change (this desktop or a /v1 client)
    // pings every window — re-pull my open-route map + the visible mailbox, debounced (SearchMailbox.render
    // has no concurrency guard; overlapping renders interleave DOM). The action-panel rerender is SKIPPED
    // while the user is mid-input in it (a half-typed rejection note must never be wiped by someone else's
    // action). A transport without the push channel (the client) just lacks the listener.
    if (window.SearchWorkflow) await window.SearchWorkflow.init();
    if (window.SearchMailbox) window.SearchMailbox.init();
    const T = window.SearchTransport;
    if (T && typeof T.onWorkflowCountsChanged === 'function') {
      let _wfPing = null;
      T.onWorkflowCountsChanged(() => {
        clearTimeout(_wfPing);
        _wfPing = setTimeout(async () => {
          try {
            await window.SearchWorkflow?.refresh?.();
            const panel = document.getElementById('preview-actions');
            const busy = panel && (panel.contains(document.activeElement)
              || (panel.querySelector('.wf-note') && panel.querySelector('.wf-note').value.trim()));
            if (!busy && window.SearchState.selectedDoc) window.SearchActions.renderActions(window.SearchState.selectedDoc);
            window.SearchMailbox?.refreshIfActive?.();
          } catch { /* best-effort */ }
        }, 400);
      });
    }
    if (opts.onWorkflowEntitled) await opts.onWorkflowEntitled();   // an optional host hook (none today)
  }
  // The permission checks above may have resolved after a doc was already selected (results populate
  // first now) — re-render its action panel so Stamp / Print / recycle appear once known.
  if (window.SearchState.selectedDoc) { try { window.SearchActions.renderActions(window.SearchState.selectedDoc); } catch {} }

  if (opts.afterInit) { try { await opts.afterInit(); } catch { /* app hook is best-effort */ } }
}

// Entry point. Installs the window-level handlers in the same order the old renderer.js did (keys,
// resizer, refocus belt), then runs the async init sequence. (Named initSearchUI, not `init`: the
// core-only search-workflow.js declares its own top-level `init` in the same global scope — the
// collision pin caught the dupe.)
function initSearchUI(opts = {}) {
  _installSearchKeys();
  _installSidebarResizer();
  _installRefocusRefresh();
  return _searchInit(opts);
}

window.SearchUI = { init: initSearchUI };
