'use strict';
// Shared state for the search UI. Consumed by all other search-ui modules.
//
// SHARED SEARCH UI (client search parity, 2026-09-13; Oracle SIGN-OFF-W/COND): this file is part of the ONE
// canonical search screen that BOTH the core Search window and the detached client's search pop-out drive.
// It reaches IO ONLY through `window.SearchTransport` (set by an adapter script loaded BEFORE these files —
// core: src/windows/search/coreTransport.js, a pure pass-through to the core's preload bridge; client: its own
// adapter over the client's preload bridge). NEVER reference either preload bridge object, Electron IPC or
// any Node module loading here — src/windows/shared/test_search_ui_no_direct_ipc.js fails the build on it (it
// scans comments too, so do not even NAME the bridge objects in this tree). The client's copy under
// client/renderer/shared/search-ui/ is GENERATED by scripts/sync-client-search.js — edit HERE only.

window.SearchState = {
  selectedDoc:  null,
  currentPages: [],
  currentPage:  0,
  entitled:     false,   // workflow add-on licensed → enhanced Search (set in SearchUI.init)
  myOpenRoutes: {},      // document_id -> open route addressed to me (workflow; set when entitled)
};

// Capability probe: a transport that cannot do X sets caps.X = false and the shared UI hides that control
// (never a dead button, never a throw). ABSENT = true, so the core adapter (every cap true) and any older
// adapter take the unchanged code path — the cap==false branches are the ONLY additions to the core's behaviour.
function _cap(name) {
  const c = window.SearchTransport && window.SearchTransport.caps;
  return !c || c[name] !== false;
}

// PURGE DIALOG TRUTH (Q1, Chris round 14 card 1, 2026-08-22): "Permanently delete … including their
// PDF files" must also say what is NOT deleted. Under `keep_processed_originals` (mig 83 ON) a filed
// document's original scan stays in the Processed folder, so the purge removes only the app's
// copies. With the switch OFF the original was already removed at filing — say nothing (the old
// sentence stays exactly as it was). Cached per window; the sentence is a suffix for the three
// purge confirms (Empty bin / Delete permanently / bulk purge).
window.SearchState = window.SearchState || {};
window.SearchState.keepOriginals = null;
window.SearchState.purgeSuffix = async function purgeSuffix() {
  try {
    if (window.SearchState.keepOriginals === null) {
      if (_cap('settings')) {
        const v = await window.SearchTransport.getSetting('keep_processed_originals');
        window.SearchState.keepOriginals = (v === 'true' || v === true);
      } else {
        window.SearchState.keepOriginals = false;   // a transport with no settings read (the client) says nothing
      }
    }
  } catch { window.SearchState.keepOriginals = false; }
  return window.SearchState.keepOriginals
    ? ' Your original scans in the Processed folder are not touched.' : '';
};


// Confidence level (shared by results + preview): '' = none, else ok/warn/err.
// Mirrors the detached client's thresholds so the two surfaces read identically.
function confLevel(c) { return c == null ? '' : c >= 85 ? 'ok' : c >= 60 ? 'warn' : 'err'; }

// Shared HTML-escape utility — used by results and preview modules. Escapes the
// five characters that can break HTML, including " and ' so values interpolated
// into attributes (e.g. title="${escHtml(...)}" in searchResults.js) stay
// contained. & is replaced first so the entity ampersands below aren't
// re-escaped. (Slashes don't break HTML attributes, so they're left intact —
// escaping them would corrupt displayed filenames like "INV.15-12-2025.pdf".)
function escHtml(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
